[2025-06-20 17:05:02] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:02] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:03] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:03] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:03] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:03] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:03] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:03] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:04] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:04] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:04] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:04] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:05] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:05] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:05] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:05] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:06] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:06] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:06] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:06] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:06] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:07] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:07] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:07] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:08] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:08] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:09] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:09] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:09] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:09] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:09] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:09] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:10] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:10] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:10] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:10] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:10] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:10] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:11] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:11] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:11] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:11] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:12] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:12] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:12] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:12] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:12] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:12] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:13] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:13] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:13] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:13] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:13] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:13] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:14] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:14] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:14] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:14] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:14] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:14] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:15] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:15] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:15] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:15] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:15] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:15] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:16] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:16] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:16] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:16] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:16] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:16] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:17] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:17] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:17] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:17] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:17] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:17] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:18] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:18] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:18] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:18] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:18] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:18] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:19] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:19] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:19] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:19] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:19] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:19] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:20] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:20] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:20] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:20] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:20] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:20] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:21] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:21] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:21] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:21] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:21] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:21] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:23] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:23] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:23] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:23] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:23] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:23] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:23] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:23] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:24] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:24] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:24] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:24] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:24] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:24] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:24] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:24] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:25] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:25] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:25] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:25] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:25] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:25] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:26] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:26] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:26] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:26] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:26] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:26] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:26] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:26] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:27] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:27] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:27] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:27] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:27] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:27] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:28] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:28] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:29] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:29] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:29] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:29] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:29] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:29] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:29] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:29] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:30] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:30] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:30] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:30] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:30] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:30] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:31] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:31] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:31] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:31] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:31] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:31] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:31] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:31] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:32] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:32] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:32] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:32] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:32] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:32] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:34] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:34] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:34] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:34] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:34] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:34] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:34] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:34] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:35] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:35] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:35] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:35] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:36] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:36] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:36] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:36] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:36] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:36] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:37] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:37] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:37] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:37] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:37] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:37] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:38] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:38] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:38] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:38] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:38] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:38] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:40] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:40] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:40] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:40] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:40] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:40] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:41] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:41] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:41] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:41] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:41] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:41] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:41] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:41] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:42] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:42] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:42] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:42] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:43] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:43] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:43] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:43] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:43] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:43] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:44] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:44] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:44] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:44] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:44] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:44] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:45] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:45] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:45] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:45] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:45] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:45] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:45] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:45] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:46] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:46] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:46] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:46] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:46] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:46] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:46] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:46] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:47] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:47] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:47] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:47] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:47] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:47] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:48] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:48] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:48] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:48] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:48] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:48] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:48] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:48] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:49] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:49] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:49] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:49] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:50] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:50] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:51] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:51] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:51] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:51] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:51] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:51] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:53] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:53] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:53] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:53] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:53] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:53] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:54] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:54] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:54] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:54] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:55] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:55] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:55] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:55] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:55] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:55] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:56] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:56] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:56] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:56] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:56] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:56] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:57] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:57] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:58] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:58] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:58] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:58] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:58] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:58] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:59] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:59] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:59] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:59] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:59] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:59] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:05:59] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:05:59] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:06:00] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:06:00] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:06:00] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:06:00] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:06:00] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:06:00] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:06:01] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:06:01] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:06:01] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:06:01] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:06:01] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:06:01] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:06:01] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:06:01] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:06:02] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:06:02] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:06:03] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:06:03] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:06:03] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:06:03] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:06:03] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:06:03] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:06:04] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:06:04] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:06:04] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:06:04] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:06:04] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:06:04] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:15] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:15] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:15] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:15] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:15] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:15] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:16] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:16] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:16] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:16] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:16] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:16] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:17] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:17] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:17] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:17] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:17] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:17] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:19] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:19] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:19] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:19] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:19] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:19] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:19] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:19] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:20] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:20] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:20] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:20] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:21] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:21] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:21] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:21] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:21] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:21] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:22] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:22] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:22] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:22] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:22] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:22] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:23] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:23] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:23] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:23] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:23] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:23] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:24] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:24] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:24] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:24] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:25] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:25] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:25] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:25] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:25] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:25] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:25] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:25] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:27] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:27] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:27] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:27] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:28] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:28] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:28] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:28] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:28] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:28] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:29] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:29] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:29] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:29] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:29] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:29] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:29] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:29] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:30] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:30] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:30] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:30] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:31] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:31] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:32] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:32] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:32] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:32] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:32] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:32] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:32] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:32] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:33] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:33] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:33] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:33] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:33] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:33] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:34] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:34] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:34] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:34] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:34] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:34] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:34] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:34] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:35] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:35] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:35] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:35] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:35] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:35] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:36] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:36] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:37] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:37] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:37] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:37] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:37] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:37] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:38] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:38] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:38] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:38] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:38] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:38] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:39] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:39] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:39] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:39] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:39] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:39] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:40] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:40] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:40] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:40] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:40] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:40] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:41] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:41] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:41] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:41] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:41] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:41] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:41] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:41] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:42] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:42] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:42] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:42] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:42] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:42] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:43] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:43] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:43] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:43] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:43] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:43] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:43] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:43] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:44] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:44] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:44] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:44] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:45] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:45] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:45] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:45] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:45] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:45] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:46] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:46] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:46] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:46] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:47] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:47] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:48] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:48] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:48] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:48] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:48] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:48] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:48] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:48] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:49] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:49] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:49] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:49] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:50] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:50] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:50] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:50] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:50] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:50] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:51] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:51] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:51] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:51] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:51] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:51] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:52] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:52] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:52] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:52] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:52] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:52] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:53] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:53] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:53] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:53] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:53] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:53] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:54] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:54] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:54] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:54] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:54] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:54] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:55] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:55] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:55] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:55] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:55] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:55] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:56] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:56] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:56] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:56] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:57] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:57] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:57] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:57] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:57] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:57] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:58] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:58] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:59] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:59] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:59] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:59] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:59] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:59] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:19:59] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:19:59] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:00] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:00] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:00] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:00] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:00] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:00] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:01] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:01] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:01] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:01] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:01] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:01] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:01] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:01] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:02] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:02] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:02] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:02] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:02] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:02] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:03] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:03] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:03] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:03] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:03] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:03] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:04] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:04] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:05] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:05] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:05] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:05] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:05] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:05] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:06] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:06] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:06] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:06] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:06] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:06] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:06] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:06] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:07] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:07] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:07] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:07] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:07] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:07] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:07] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:07] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:08] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:08] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:08] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:08] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:09] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:09] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:09] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:09] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:09] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:09] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:09] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:09] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:10] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:10] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:10] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:10] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:10] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:10] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:11] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:11] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:11] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:11] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:11] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:11] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:12] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:12] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:12] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:12] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:13] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:13] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:13] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:13] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:13] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:13] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:14] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:14] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:14] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:14] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:14] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:14] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:14] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:14] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:15] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:15] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:15] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:15] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:15] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:15] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:16] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:16] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:16] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:16] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:16] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:16] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:17] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:17] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:17] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:17] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:18] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:18] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:19] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:19] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:19] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:19] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:19] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:19] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:19] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:19] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:20] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:20] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:20] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:20] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:20] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:20] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:20] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:20] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:21] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:21] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:21] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:21] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:21] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:21] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:22] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:22] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:22] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:22] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:23] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:23] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:23] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:23] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:23] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:23] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:24] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:24] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:24] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:24] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:24] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:24] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:24] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:24] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:25] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:25] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:25] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:25] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:25] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:25] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:25] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:25] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:26] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:26] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:26] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:26] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:26] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:26] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:27] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:27] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:28] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:28] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:28] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:28] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:28] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:28] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:29] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:29] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:29] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:29] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:29] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:29] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:29] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:29] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:30] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:30] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:30] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:30] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:30] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:30] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:30] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:30] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:31] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:31] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:32] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:32] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:32] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:32] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:32] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:32] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:32] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:32] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:33] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:33] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:33] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:33] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:33] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:33] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:34] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:34] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:34] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:34] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:34] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:34] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:34] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:34] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:35] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:35] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:36] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:36] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:36] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:36] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:36] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:36] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:36] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:36] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:37] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:37] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:37] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:37] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:37] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:37] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:37] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:37] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:39] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:39] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:39] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:39] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:39] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:39] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:39] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:39] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:40] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:40] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:40] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:40] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:40] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:40] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:41] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:41] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:41] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:41] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:41] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:41] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:41] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:41] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:42] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:42] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:42] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:42] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:42] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:42] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:43] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:43] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:44] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:44] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:44] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:44] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:44] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:44] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:45] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:45] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:45] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:45] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:45] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:45] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:46] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:46] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:46] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:46] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:46] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:46] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:46] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:46] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:47] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:47] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:47] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:47] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:47] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:47] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:47] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:47] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:48] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:48] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:49] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:49] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:49] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:49] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:49] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:49] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:50] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:50] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:50] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:50] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:50] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:50] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:51] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:51] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:51] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:51] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:52] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:52] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:52] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:52] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:52] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:52] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:52] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:52] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:53] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:53] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:53] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:53] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:54] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:54] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:54] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:54] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:54] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:54] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:55] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:55] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:55] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:55] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:55] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:55] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:56] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:56] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:56] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:56] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:56] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:56] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:57] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:57] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:58] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:58] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:58] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:58] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:58] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:58] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:20:59] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:20:59] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:21:00] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:21:00] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:21:00] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:21:00] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:21:00] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:21:00] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:21:01] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:21:01] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:21:01] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:21:01] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:21:01] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:21:01] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:21:01] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:21:01] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:21:02] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:21:02] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:21:03] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:21:03] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:21:03] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:21:03] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:21:03] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:21:03] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:21:04] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:21:04] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:21:04] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:21:04] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:21:04] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:21:04] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:21:04] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:21:04] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:21:05] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:21:05] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
[2025-06-20 17:21:05] 쿼리후 데이터 전처리 및 예측 시 오류발생
[2025-06-20 17:21:05] Exception encountered when calling PatchEmbedding.call().

[1munsupported operand type(s) for //: 'NoneType' and 'int'[0m

Arguments received by PatchEmbedding.call():
  • x=tf.Tensor(shape=(1, None, 37), dtype=float32)
